In [2]:
import os
import json
import pandas as pd
import psycopg2

In [3]:
# Dataframe of aggregated Insurance

path1="C:/Users/pc/Desktop/Phonepe/pulse/data/aggregated/insurance/country/india/state/"
agg_insur_list= os.listdir(path1)


columns1= {"State":[], "Year":[], "Quarter":[], "Insurance_type":[], "Insurance_count":[],"Insurance_amount":[] }

for state in agg_insur_list:
    cur_states =path1+state+"/"
    agg_year_list = os.listdir(cur_states)
    
    for year in agg_year_list:
        cur_years = cur_states+year+"/"
        agg_file_list = os.listdir(cur_years)

        for file in agg_file_list:
            cur_files = cur_years+file
            data = open(cur_files,"r")
            A = json.load(data)

            for i in A["data"]["transactionData"]:
                name = i["name"]
                count = i["paymentInstruments"][0]["count"]
                amount = i["paymentInstruments"][0]["amount"]
                columns1["Insurance_type"].append(name)
                columns1["Insurance_count"].append(count)
                columns1["Insurance_amount"].append(amount)
                columns1["State"].append(state)
                columns1["Year"].append(year)
                columns1["Quarter"].append(int(file.strip(".json")))


aggre_insurance = pd.DataFrame(columns1)

aggre_insurance["State"]=aggre_insurance["State"].str.replace("andaman-&-nicobar-islands","Andaman & Nicobar")
aggre_insurance["State"]=aggre_insurance["State"].str.replace("-"," ")
aggre_insurance["State"]=aggre_insurance["State"].str.title()
aggre_insurance['State']=aggre_insurance['State'].str.replace("Dadra & Nagar Haveli & Daman & Diu", "Dadra and Nagar Haveli and Daman and Diu")

In [ ]:
aggre_insurance

In [5]:
# Dataframe of aggregated Transactions

path2="C:/Users/pc/Desktop/Phonepe/pulse/data/aggregated/transaction/country/india/state/"
agg_tran_list=os.listdir(path2)

columns2={"State": [], "Year": [], "Quarter": [], "Transaction_type": [], "Transaction_count": [],
            'Transaction_amount': []}

for state in agg_tran_list:
    cur_states=path2+state+"/"
    agg_year_list=os.listdir(cur_states)

    for year in agg_year_list:
        cur_year=cur_states+year+"/"
        agg_file_list=os.listdir(cur_year)

        for file in agg_file_list:
            cur_file=cur_year+file 
            data=open(cur_file,"r")

            B=json.load(data)

            for i in B["data"]["transactionData"]:
                name = i["name"]
                count = i["paymentInstruments"][0]["count"]
                amount = i["paymentInstruments"][0]["amount"]
                columns2["Transaction_type"].append(name)
                columns2["Transaction_count"].append(count)
                columns2["Transaction_amount"].append(amount)
                columns2["State"].append(state)
                columns2["Year"].append(year)
                columns2["Quarter"].append(int(file.strip(".json")))

aggre_transaction = pd.DataFrame(columns2)

aggre_transaction["State"]=aggre_transaction["State"].str.replace("andaman-&-nicobar-islands","Andaman & Nicobar")
aggre_transaction["State"]=aggre_transaction["State"].str.replace("-"," ")
aggre_transaction["State"]=aggre_transaction["State"].str.title()
aggre_transaction['State']=aggre_transaction['State'].str.replace("Dadra & Nagar Haveli & Daman & Diu", "Dadra and Nagar Haveli and Daman and Diu")

In [ ]:
aggre_transaction

In [7]:
# Dataframe of aggregated User

path3="C:/Users/pc/Desktop/Phonepe/pulse/data/aggregated/user/country/india/state/"
agg_user_list=os.listdir(path3)

columns3={"State": [], "Year": [], "Quarter": [], "Brands": [], "Transaction_count": [],
            "Percentage": []}

for state in agg_user_list:
    cur_states=path3+state+"/"
    agg_year_list=os.listdir(cur_states)

    for year in agg_year_list:
        cur_year=cur_states+year+"/"
        agg_file_list=os.listdir(cur_year)

        for file in agg_file_list:
            cur_file=cur_year+file 
            data=open(cur_file,"r")

            C=json.load(data)
            
            try:
                for i in C["data"]["usersByDevice"]:
                    brand = i["brand"]
                    count = i["count"]
                    percentage = i["percentage"]
                    columns3["Brands"].append(brand)
                    columns3["Transaction_count"].append(count)
                    columns3["Percentage"].append(percentage)
                    columns3["State"].append(state)
                    columns3["Year"].append(year)
                    columns3["Quarter"].append(int(file.strip(".json")))


            except:
                pass

aggre_user = pd.DataFrame(columns3)

aggre_user["State"] = aggre_user["State"].str.replace("andaman-&-nicobar-islands","Andaman & Nicobar")
aggre_user["State"] = aggre_user["State"].str.replace("-"," ")
aggre_user["State"] = aggre_user["State"].str.title()
aggre_user['State'] = aggre_user['State'].str.replace("Dadra & Nagar Haveli & Daman & Diu", "Dadra and Nagar Haveli and Daman and Diu")

In [ ]:
aggre_user

In [28]:
# Dataframe of Map Insurance

path4="C:/Users/pc/Desktop/Phonepe/pulse/data/map/insurance/hover/country/india/state/"
map_insur_list= os.listdir(path4)

columns4= {"State":[], "Year":[], "Quarter":[], "District":[], "Transaction_count":[],"Transaction_amount":[] }

for state in map_insur_list:
    cur_states =path4+state+"/"
    agg_year_list = os.listdir(cur_states)
    
    for year in agg_year_list:
        cur_years = cur_states+year+"/"
        agg_file_list = os.listdir(cur_years)

        for file in agg_file_list:
            cur_files = cur_years+file
            data = open(cur_files,"r")
            D = json.load(data)

            for i in D["data"]["hoverDataList"]:
                name = i["name"]
                count = i["metric"][0]["count"]
                amount = i["metric"][0]["amount"]
                columns4["District"].append(name)
                columns4["Transaction_count"].append(count)
                columns4["Transaction_amount"].append(amount)
                columns4["State"].append(state)
                columns4["Year"].append(year)
                columns4["Quarter"].append(int(file.strip(".json")))


map_insurance = pd.DataFrame(columns4)

map_insurance["State"] = map_insurance["State"].str.replace("andaman-&-nicobar-islands","Andaman & Nicobar")
map_insurance["State"] = map_insurance["State"].str.replace("-"," ")
map_insurance["State"] = map_insurance["State"].str.title()
map_insurance['State'] = map_insurance['State'].str.replace("Dadra & Nagar Haveli & Daman & Diu", "Dadra and Nagar Haveli and Daman and Diu")

In [ ]:
map_insurance

In [30]:
# Dataframe of Map Transactions

path5="C:/Users/pc/Desktop/Phonepe/pulse/data/map/transaction/hover/country/india/state/"
map_tran_list=os.listdir(path5)

columns5={"State": [], "Year": [], "Quarter": [], "District": [], "Transaction_count": [],
            "Transaction_amount": []}

for state in map_tran_list:
    cur_states=path5+state+"/"
    map_year_list=os.listdir(cur_states)

    for year in map_year_list:
        cur_year=cur_states+year+"/"
        map_file_list=os.listdir(cur_year)

        for file in map_file_list:
            cur_file=cur_year+file 
            data=open(cur_file,"r")

            E=json.load(data)

            for i in E['data']["hoverDataList"]:
                name = i["name"]
                count = i["metric"][0]["count"]
                amount = i["metric"][0]["amount"]
                columns5["District"].append(name)
                columns5["Transaction_count"].append(count)
                columns5["Transaction_amount"].append(amount)
                columns5["State"].append(state)
                columns5["Year"].append(year)
                columns5["Quarter"].append(int(file.strip(".json")))

map_transaction = pd.DataFrame(columns5)

map_transaction["State"] = map_transaction["State"].str.replace("andaman-&-nicobar-islands","Andaman & Nicobar")
map_transaction["State"] = map_transaction["State"].str.replace("-"," ")
map_transaction["State"] = map_transaction["State"].str.title()
map_transaction['State'] = map_transaction['State'].str.replace("Dadra & Nagar Haveli & Daman & Diu", "Dadra and Nagar Haveli and Daman and Diu")

In [ ]:
map_transaction

In [32]:
# Dataframe of Map User

path6="C:/Users/pc/Desktop/Phonepe/pulse/data/map/user/hover/country/india/state/"
map_user_list=os.listdir(path6)


columns6={"State": [], "Year": [], "Quarter": [], "District":[], "RegisteredUser":[], "AppOpens":[]}

for state in map_user_list:
    cur_states=path6+state+"/"
    map_year_list=os.listdir(cur_states)

    for year in map_year_list:
        cur_year=cur_states+year+"/"
        map_file_list=os.listdir(cur_year)

        for file in map_file_list:
            cur_file=cur_year+file 
            data=open(cur_file,"r")

            F=json.load(data)

            for i in F["data"]["hoverData"].items():
                district = i[0]
                registereduser = i[1]["registeredUsers"]
                appopens = i[1]["appOpens"]
                columns6["District"].append(district)
                columns6["RegisteredUser"].append(registereduser)
                columns6["AppOpens"].append(appopens)
                columns6["State"].append(state)
                columns6["Year"].append(year)
                columns6["Quarter"].append(int(file.strip(".json")))

map_user = pd.DataFrame(columns6)

map_user["State"] = map_user["State"].str.replace("andaman-&-nicobar-islands","Andaman & Nicobar")
map_user["State"] = map_user["State"].str.replace("-"," ")
map_user["State"] = map_user["State"].str.title()
map_user['State'] = map_user['State'].str.replace("Dadra & Nagar Haveli & Daman & Diu", "Dadra and Nagar Haveli and Daman and Diu")

In [ ]:
map_user

In [15]:
# Dataframe of Top Insurance

path7="C:/Users/pc/Desktop/Phonepe/pulse/data/top/insurance/country/india/state/"
top_insur_list=os.listdir(path7)

columns7={"State":[], "Year":[], "Quarter":[], "Pincodes":[], "Transaction_count":[], "Transaction_amount":[]}

for state in top_insur_list:
    cur_states = path7+state+"/"
    top_year_list = os.listdir(cur_states)

    for year in top_year_list:
        cur_years = cur_states+year+"/"
        top_file_list = os.listdir(cur_years)

        for file in top_file_list:
            cur_files = cur_years+file
            data = open(cur_files,"r")
            G = json.load(data)

            for i in G["data"]["pincodes"]:
                entityName = i["entityName"]
                count = i["metric"]["count"]
                amount = i["metric"]["amount"]
                columns7["Pincodes"].append(entityName)
                columns7["Transaction_count"].append(count)
                columns7["Transaction_amount"].append(amount)
                columns7["State"].append(state)
                columns7["Year"].append(year)
                columns7["Quarter"].append(int(file.strip(".json")))

top_insur = pd.DataFrame(columns7)

top_insur["State"] = top_insur["State"].str.replace("andaman-&-nicobar-islands","Andaman & Nicobar")
top_insur["State"] = top_insur["State"].str.replace("-"," ")
top_insur["State"] = top_insur["State"].str.title()
top_insur['State'] = top_insur['State'].str.replace("Dadra & Nagar Haveli & Daman & Diu", "Dadra and Nagar Haveli and Daman and Diu")

In [ ]:
top_insur

In [17]:
# Dataframe of Top Transactions

path8="C:/Users/pc/Desktop/Phonepe/pulse/data/top/transaction/country/india/state/"
top_tran_list = os.listdir(path8)

columns8 = {"State":[], "Year":[], "Quarter":[], "Pincodes":[], "Transaction_count":[], "Transaction_amount":[]}

for state in top_tran_list:
    cur_states = path8+state+"/"
    top_year_list = os.listdir(cur_states)
    
    for year in top_year_list:
        cur_years = cur_states+year+"/"
        top_file_list = os.listdir(cur_years)
        
        for file in top_file_list:
            cur_files = cur_years+file
            data = open(cur_files,"r")
            H = json.load(data)

            for i in H["data"]["pincodes"]:
                entityName = i["entityName"]
                count = i["metric"]["count"]
                amount = i["metric"]["amount"]
                columns8["Pincodes"].append(entityName)
                columns8["Transaction_count"].append(count)
                columns8["Transaction_amount"].append(amount)
                columns8["State"].append(state)
                columns8["Year"].append(year)
                columns8["Quarter"].append(int(file.strip(".json")))

top_transaction = pd.DataFrame(columns8)

top_transaction["State"] = top_transaction["State"].str.replace("andaman-&-nicobar-islands","Andaman & Nicobar")
top_transaction["State"] = top_transaction["State"].str.replace("-"," ")
top_transaction["State"] = top_transaction["State"].str.title()
top_transaction["State"] = top_transaction["State"].str.replace("Dadra & Nagar Haveli & Daman & Diu", "Dadra and Nagar Haveli and Daman and Diu")

In [ ]:
top_transaction

In [19]:
# Dataframe of Top User

path9="C:/Users/pc/Desktop/Phonepe/pulse/data/top/user/country/india/state/"
top_user_list=os.listdir(path9)

columns9 = {"State":[], "Year":[], "Quarter":[], "Pincodes":[], "RegisteredUser":[]}

for state in top_user_list:
    cur_states = path9+state+"/"
    top_year_list = os.listdir(cur_states)

    for year in top_year_list:
        cur_year = cur_states+year+"/"
        top_file_list = os.listdir(cur_year)

        for file in top_file_list:
            cur_file = cur_year+file
            data = open(cur_file,"r")
            I = json.load(data)

            for i in I["data"]["pincodes"]:
                name = i["name"]
                registeredusers = i["registeredUsers"]
                columns9["Pincodes"].append(name)
                columns9["RegisteredUser"].append(registereduser)
                columns9["State"].append(state)
                columns9["Year"].append(year)
                columns9["Quarter"].append(int(file.strip(".json")))

top_user = pd.DataFrame(columns9)

top_user["State"] = top_user["State"].str.replace("andaman-&-nicobar-islands","Andaman & Nicobar")
top_user["State"] = top_user["State"].str.replace("-"," ")
top_user["State"] = top_user["State"].str.title()
top_user["State"] = top_user["State"].str.replace("Dadra & Nagar Haveli & Daman & Diu", "Dadra and Nagar Haveli and Daman and Diu")

In [ ]:
top_user

In [35]:
# Table Creation 

# SQL Connection


mydb=psycopg2.connect(host="localhost",
                    user="postgres",
                    password="rihana",
                    database="phonepe_data",
                    port="5432")
cursor=mydb.cursor()

#Aggregated Insurance Table
create_query1= '''CREATE TABLE if not exists aggregated_insurance (State varchar(50),
                                                                      Year int,
                                                                      Quarter int,
                                                                      Insurance_type varchar(50),
                                                                      Insurance_count bigint,
                                                                      Insurance_amount bigint
                                                                      )'''
cursor.execute(create_query1)
mydb.commit()

insert_query1 = '''INSERT INTO aggregated_insurance (State, Year, Quarter, Insurance_type, Insurance_count, Insurance_amount)
                                                        values(%s,%s,%s,%s,%s,%s)'''



data=aggre_insurance.values.tolist()
cursor.executemany(insert_query1,data)
mydb.commit()

#Aggregated Transaction Table
create_query2='''CREATE TABLE if not exists aggregated_transaction (State varchar(50),
                                                                      Year int,
                                                                      Quarter int,
                                                                      Transaction_type varchar(50),
                                                                      Transaction_count bigint,
                                                                      Transaction_amount bigint
                                                                      )'''
cursor.execute(create_query2)
mydb.commit()

insert_query2= '''INSERT INTO aggregated_transaction (State, Year, Quarter, Transaction_type, 
                                                       Transaction_count, Transaction_amount)
                                                        values(%s,%s,%s,%s,%s,%s)'''



data=aggre_transaction.values.tolist()
cursor.executemany(insert_query2,data)
mydb.commit()

#Aggregated User Table
create_query3 = '''CREATE TABLE if not exists aggregated_user (State varchar(50),
                                                                Year int,
                                                                Quarter int,
                                                                Brands varchar(50),
                                                                Transaction_count bigint,
                                                                Percentage float)'''
cursor.execute(create_query3)
mydb.commit()

insert_query3= '''INSERT INTO aggregated_user (State, Year, Quarter, Brands, Transaction_count, Percentage)
                                                    values(%s,%s,%s,%s,%s,%s)'''


data=aggre_user.values.tolist()
cursor.executemany(insert_query3,data)
mydb.commit()

In [36]:
# Map Insurance Table

mydb=psycopg2.connect(host="localhost",
                    user="postgres",
                    password="rihana",
                    database="phonepe_data",
                    port="5432")
cursor=mydb.cursor()

create_query4 = '''CREATE TABLE if not exists map_insurance (State varchar(50),
                                                                Year int,
                                                                Quarter int,
                                                                District varchar(50),
                                                                Transaction_count bigint,
                                                                Transaction_amount float)'''
cursor.execute(create_query4)
mydb.commit()

insert_query4 = '''INSERT INTO map_insurance (State, Year, Quarter, District, Transaction_count, Transaction_amount)
                    VALUES (%s, %s, %s, %s, %s, %s)'''

data=map_insurance.values.tolist()
cursor.executemany(insert_query4,data)
mydb.commit()

In [37]:
# Map Transaction Table

mydb=psycopg2.connect(host="localhost",
                    user="postgres",
                    password="rihana",
                    database="phonepe_data",
                    port="5432")
cursor=mydb.cursor()

create_query5 = '''CREATE TABLE if not exists map_transaction (State varchar(50),
                                                                Year int,
                                                                Quarter int,
                                                                District varchar(50),
                                                                Transaction_count bigint,
                                                                Transaction_amount float)'''
cursor.execute(create_query5)
mydb.commit()

insert_query5 = '''INSERT INTO map_Transaction (State, Year, Quarter, District, Transaction_count, Transaction_amount)
                    VALUES (%s, %s, %s, %s, %s, %s)'''


data=map_transaction.values.tolist()
cursor.executemany(insert_query5,data)
mydb.commit()

In [38]:
# Map User Table

mydb=psycopg2.connect(host="localhost",
                    user="postgres",
                    password="rihana",
                    database="phonepe_data",
                    port="5432")
cursor=mydb.cursor()

create_query6= '''CREATE TABLE if not exists map_user (State varchar(50),
                                                        Year int,
                                                        Quarter int,
                                                        District varchar(50),
                                                        RegisteredUser bigint,
                                                        AppOpens bigint)'''
cursor.execute(create_query6)
mydb.commit()

insert_query6 = '''INSERT INTO map_user (State, Year, Quarter, District, RegisteredUser, AppOpens)
                        values(%s,%s,%s,%s,%s,%s)'''

data=map_user.values.tolist()
cursor.executemany(insert_query6,data)
mydb.commit()

In [40]:
# Top Insurance Table 

mydb=psycopg2.connect(host="localhost",
                    user="postgres",
                    password="rihana",
                    database="phonepe_data",
                    port="5432")
cursor=mydb.cursor()

create_query7 = '''CREATE TABLE if not exists top_insurance (State varchar(50),
                                                                Year int,
                                                                Quarter int,
                                                                Pincode int,
                                                                Transaction_count bigint,
                                                                Transaction_amount bigint)'''
cursor.execute(create_query7)
mydb.commit()

insert_query7 = '''INSERT INTO top_insurance (State, Year, Quarter, Pincode, Transaction_count, Transaction_amount)
                 values(%s,%s,%s,%s,%s,%s)'''

data=top_insur.values.tolist()
cursor.executemany(insert_query7,data)
mydb.commit()

In [41]:
# Top Transaction Table

mydb=psycopg2.connect(host="localhost",
                    user="postgres",
                    password="rihana",
                    database="phonepe_data",
                    port="5432")
cursor=mydb.cursor()

create_query8 = '''CREATE TABLE if not exists top_transaction (State varchar(50),
                                                                Year int,
                                                                Quarter int,
                                                                pincode int,
                                                                Transaction_count bigint,
                                                                Transaction_amount bigint)'''
cursor.execute(create_query8)
mydb.commit()

insert_query8 = '''INSERT INTO top_transaction (State, Year, Quarter, Pincode, Transaction_count, Transaction_amount)
                    values(%s,%s,%s,%s,%s,%s)'''

data=top_transaction.values.tolist()
cursor.executemany(insert_query8,data)
mydb.commit()

In [42]:
# Top User Table

mydb=psycopg2.connect(host="localhost",
                    user="postgres",
                    password="rihana",
                    database="phonepe_data",
                    port="5432")
cursor=mydb.cursor()

create_query9= '''CREATE TABLE if not exists top_user (State varchar(50),
                                                        Year int,
                                                        Quarter int,
                                                        Pincode int,
                                                        RegisteredUser bigint
                                                        )'''
cursor.execute(create_query9)
mydb.commit()

insert_query9 = '''INSERT INTO top_user (State, Year, Quarter, Pincode, RegisteredUser)
                    values(%s,%s,%s,%s,%s)'''

data=top_user.values.tolist()
cursor.executemany(insert_query9,data)
mydb.commit()